### ISSUE TITLE
Crear texto para "Nuestra comunidad"

### ISSUE THREAD

**Issue by cyncyncyn** [linuxchixar/web#1]
Crear texto de un párrafo que resuma cómo está compuesta nuestra comunidad para la home

**Comment by cyncyncyn** [comment]
Comunidad para visibilizar mujeres del mundo GNU/Linux y del FOSS, y para todos aquellos que ayudan a disminuir la brecha de género. #linuxchixar en freenode

**Comment by cyncyncyn** [comment]
Somos un grupo de mujeres y hombres con diferentes perfiles dentro del ámbito de la tecnología en Argentina.- Developers, admins, operators, estudiantes... todos son bienvenidos.

**Comment by vkmc** [comment]
Texto agregado :+1:
