### ISSUE TITLE
Crear texto para "Nuestro objetivo"

### ISSUE THREAD

**Issue by cyncyncyn** [linuxchixar/web#2]
Definir y redactar en un párrafo el objetivo de la comunidad para la home

**Comment by cyncyncyn** [comment]
Nuestro grupo comenzó como un esfuerzo por reunir mujeres que se encuentren trabajando con tecnologías libres, y hoy por hoy, estamos intentando promover que más mujeres de diferentes ámbitos relacionados con la tecnología se involucren en este campo.

**Comment by vkmc** [comment]
Texto agregado :+1:
