### ISSUE TITLE
Crear texto para "Nuestro plan"

### ISSUE THREAD

**Issue by cyncyncyn** [linuxchixar/web#3]
Definir un plan para lograr los objetivos, y plasmarlo en un párrafo para la home

**Comment by cyncyncyn** [comment]
Buscamos crear un espacio que haga que más mujeres se animen a dar sus primeros pasos en el software libre, y desde ese punto empiecen a participar de otras comunidades. Para esto, estaremos ayudando a la difusión de oportunidades laborales y de capacitación, y además participaremos en la organización de reuniones, talleres y conferencias que tengan como objetivo principal aumentar la inclusión.

**Comment by vkmc** [comment]
Texto agregado :+1:
